name: astrods

channels:
- conda-forge

dependencies:
- python=3.9.*

# A linux desktop environment
- websockify

- numpy==1.22.*
- matplotlib==3.5.*
- graphviz>=2.50.0
- psycopg2==2.9.*
- pytorch>=1.10.0
- pytorch-lightning
- pyaudio>=0.2.11
- cython
- protobuf
- mpich
- mpi4py
- cartopy
- mkl-service

- pip

- pip:
  - jupyter-desktop-server==0.1.3
  - tensorflow>=2.7.*
  - opencv-python>=4.5.5.62
  - nose2>=0.10.0
  - sympy
  - scipy
  - scikit-learn==1.0.*
  - scikit-image==0.19.*
  - beautifulsoup4
  - tqdm
  - h5py
  - netcdf4
  - numexpr
  - corner==2.2.*
  - dask>=2021.12.0
  - dask-ml>=2021.11.30
  - distributed>=2021.12.0
  - jaxlib>=0.1.75
  - SQLAlchemy>=1.4.29
  - xarray>=0.20.2
  - nltk>=3.6.7
  - seaborn>=0.11.2
  - bqplot>=0.12.31
  - astroquery>=0.4.5
  - astropy>=5.0
  - dustmaps>=1.0.9
  - pyvo>=1.2
  - joblib>=1.1.0
  - aesara>=2.3.4
  - pymc3>=3.11.4
  - requests>=2.27.1
  - ipycanvas
  - altair>=4.2.0
  - vega3>=0.13.0
  - pytz>=2021.3
  - keras==2.8.*
  - scikeras
  - keras-preprocessing>=1.1.0
  - tensorflow-io-gcs-filesystem>=0.23.0
  - lightkurve
  - ipyparallel>=8.1.0
  - jupyter-tensorboard>=0.2.0
  - line_profiler>-3.4.0
  - snakeviz>=2.1.1
  - memory_profiler>=0.60.0
  - flask>=2.0.2
  - stsci.tools>=4.0.0
  - gensim>=4.1.2
  - tweet-preprocessor
  - pyLDAvis>=3.3.1
  - umap-learn>=0.5.2
  - pydot>=1.4.0
  - TPOT>=0.11.7
  - tables>=3.7.0
  - aiohttp>=3.8.1
  - jax
  - watermark
  - autopep8
  - datashader==0.13.0
  - holoviews==1.14.7
  - hvplot==0.7.3
  - vega_datasets
  - vega
  - pythreejs
  - ipywidgets
  - ipyvolume
  - pandas-bokeh
  - click
  - fire
  - pycodestyle
  - flake8
  - nb_black
  - pycodestyle_magic
  - twine